apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "changeme_root"
  MYSQL_USER: "tienda_user"
  MYSQL_PASSWORD: "changeme_pass"
  DB_USER: "tienda_user"
  DB_PASSWORD: "changeme_pass"